# Generated by Django 4.2.9 on 2024-02-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_title_alter_task_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='limit_date',
            field=models.DateField(blank=True, null=True, verbose_name='期限'),
        ),
    ]
